worker:
  health: /server-health
  balance:
    - path: /process
      method: POST

app:
  serve: http # socket or http
  port: 4999
  socket: /tmp/balancer.sock
  cookie: MUXSESSION
  session_lifetime: 600 # in seconds
  
redis: 
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

api:
  port: 8558
  token: Cc8zpRuLxXgG6wZDe5sr9hYqMkFK74nT