worker:
  health: /server-health

app:
  serve: http # socket or http
  port: 4999
  socket: /tmp/balancer.sock
  cookie: MUXSESSION
  session_lifetime: 600 # in seconds

redis: 
  addr: 127.0.0.1:6379
  password:
  db: 0
